services:
  - name: lstm-service
    image: python:3.8-slim
    env:
      PORT: 5000
    deploy:
      command: python app.py
      resources:
        cpu: 1000
        memory: 512
    volumes:
      - ./my_model.h5:/app/my_model.h5
      - ./scaler.pkl:/app/scaler.pkl
